name: "Setup environment with Node + Github NPM"
description: "Authenticate and install packages"
branding:
  icon: "terminal"
  color: "blue"
inputs:
  NPM_TOKEN:
    description: "Github npm registry token"
    required: true
  NPM_REGISTRY_ORG:
    description: "Github npm registry org"
    required: true
  NODE_VERSION:
    description: "Node version"
    required: true
  INSTALL_NODE_DEPS:
    description: "Flag to install npm dependencies"
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: Set node version
      uses: actions/setup-node@v3
      with:
        node-version: ${{ input.NODE_VERSION }}
        cache: yarn
    - name: Create .npmrc
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.NPM_TOKEN }}" > .npmrc
        echo "@${{ inputs.NPM_REGISTRY_ORG }}:registry=https://npm.pkg.github.com/" >> .npmrc
        echo "always-auth=true" >> .npmrc
      shell: bash
    - name: Install npm dependencies
      if: ${{ inputs.INSTALL_NODE_DEPS == 'true' }}
      run: yarn install --immutable
      shell: bash
