name: "Setup environment with Node + Python + Github NPM"
description: "Authenticate and install packages"
branding:
  icon: "terminal"
  color: "blue"
inputs:
  NPM_TOKEN:
    description: "Github npm registry token"
    required: true
  NPM_REGISTRY_ORG:
    description: "Github npm registry org"
    required: true
  NODE_VERSION:
    description: "Node version"
    required: false
  PYTHON_VERSION:
    description: "Python version"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set node version
      if: ${{ inputs.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        cache: yarn
    - name: Set up python
      if: ${{ inputs.PYTHON_VERSION }}
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.9
    - name: Install Poetry
      if: ${{ inputs.PYTHON_VERSION }}
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false
    - name: Create .npmrc
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.NPM_TOKEN }}" > .npmrc
        echo "@${{ inputs.NPM_REGISTRY_ORG }}:registry=https://npm.pkg.github.com/" >> .npmrc
        echo "always-auth=true" >> .npmrc
      shell: bash
    - name: Install npm dependencies
      if: ${{ inputs.NODE_VERSION }}
      run: yarn install --immutable
      shell: bash
