name: "Handle sync cache"
description: "Handle cache for env sync workflows"
inputs:
  cache-file:
    required: true
  cache-key:
    required: true
  ref:
    required: true
  sha:
    required: true
  restore:
    required: false

runs:
  using: "node16"
  main: "index.js"
  post: "cleanup.js"
